SystemUI: Declare new permissions for VPN tile
The qs tile refuses to present itself with log stating
java.lang.SecurityException: Requires one of the following permissions:
android.permission.NETWORK_STACK,
android.permission.MAINLINE_NETWORK_STACK.

Fix this issue.
Change-Id: I6366c75d2c52eb8b53212037d0d83db2c40d7abb

Change-Id: I35f23073a2066f8a4a88721af62caaf8dc1383d9