Bug fixes - a lot (#7)
* storage: Set all sdcards to visible

If they are visibile to apps the media scanner will scan them.

Change-Id: Icceceafc8469b6b9d1c0e72f8425d7e38ae4a10b
Signed-off-by: AKabhishek <abhishekkaushik.star@gmail.com>

* Use Auto brightness for Ambient Display

this works well now

Change-Id: I57b28e4b3aa3e79940cc84f12267f6607d6ab3bc
Signed-off-by: AKabhishek <abhishekkaushik.star@gmail.com>

* Ambient Music: don't trigger it when no media info are available

now that we have ambient bottom battery level, we can notice that
ambient music is triggered even if track info are null (the screen shows
only the battery level at bottom and nothing else).

Catched thanks to kdeconnect media notification (it doesn't have
track infos but still changes mediasession playing state).

Change-Id: I2b1998f402aced38c12b9deb77acc16ad455941c
Signed-off-by: AKabhishek <abhishekkaushik.star@gmail.com>

* QS: add right/left padding even if it's 0 for collapsed statusbar

For devices without a rounded display we are setting rounded_corner_content_padding
to 0 to avoid useless left/right padding in the statusbar.
But this looks odd in the expanded statusbar / qs panel because other elements
like the brightness slider buttons or the date have the padding anyway.

We can handle those cases separately.

Thanks @anirudhgupta109 for the suggestion.

Change-Id: I77d6f10a8fb0c5a529f43ea6311bc98e37815106
Signed-off-by: rk2810 <rohan.kumquat@gmail.com>
Signed-off-by: Ded_Boi <dhanush911gtr@gmail.com>

* Fix text cutting off during shutdown animation

No better way to explain it than through a picture

https://i.imgur.com/nvcoYEz.jpg

Google some how did not account for what I like to call 'Can't see
shit mode' and so this happened :p

Change-Id: I126bb38c6c9d334eef2520128348639ed609d701
Signed-off-by: rk2810 <rohan.kumquat@gmail.com>

* Ensure Recents FAB respects RTL

- When using Gravity you should use END and START opposed to RIGHT and LEFT
to maintain RTL working as it should.

Change-Id: Ic89f4a8e05c1ea3ead98fe27b4eb214ea1b63c6f
Signed-off-by: rk2810 <rohan.kumquat@gmail.com>

* Use Cloudflare DNS servers as defaults for tethering

Cloudflare DNS has a better privacy policy than Google Public DNS and
has DNS-over-TLS and DNS-over-HTTPS so it won't be a downgrade when
Android ships one of them.

Change-Id: I29511960f286a49cf8c9899fa373690458940d87

* Use Cloudflare DNS as the default fallback

Cloudflare DNS has a better privacy policy than Google Public DNS and
has DNS-over-TLS and DNS-over-HTTPS so it won't be a downgrade when
Android ships one of them.

Change-Id: I102b3e268f10257a4f0be45e77d222780d7273be

* Relax Instant Apps Settings whitelist enforcement

The strict whitelist of settings for Instant Apps is leading to too much
unintended breakage, remove the enforcement until better infrastructure
can be added to make sure settings that should be whitelisted are.

Bug: 71009655
Test: Coming in a follow up

(cherry picked from commit b6108d621002d4de708ae526e7c2bc95dabef080)

Change-Id: Iaa1d71331407cee86c10105c1e5668ffd0c925a1

* Use Cloudflare DNS servers as hints

Cloudflare DNS has a better privacy policy than Google Public DNS and
has DNS-over-TLS and DNS-over-HTTPS so it won't be a downgrade when
Android ships one of them.

Change-Id: Ia0fe7c25583415344637de9b8402b161d442a980

* NetworkDiagnostics: switch to Cloudflare DNS

Cloudflare DNS has a better privacy policy than Google Public DNS and
has DNS-over-TLS and DNS-over-HTTPS so it won't be a downgrade when
Android ships one of them.

Change-Id: Ida24063569cd53d285fae1a9a445b887b603e722

* [AWARE] Make PeerHandle comparable/hashable

Add public equals()/hash() methods to PeerHandle. Allows the handle to
be used across multiple calls/sessions.

(partial cherry-pick of commit 3d33d7495ffbf12966299df8359d71a6f0926e7a)
(cherry-pick of commit 0d49c0dda8bfef0267d81e8490e4882e51a15af4)

Bug: 68931709
Test: builds, unit test, integration test
Change-Id: I87df50edb948a7afc90e496165013235ddca1e48

* Handle onBindingDied in notification manager

On Android, if the process containing the service being bound to
crashes before the bind succeeds, the app doing the binding won't
get a success or failure callback.

When that happens in this code, this leaves notif. manager thinking
that a binding is in progress, so it never attempts to rebind until
the device is rebooted.

Bug: 69064494
Test: manual, crashed listener on proc start, verified not unbound forever
Change-Id: Id2082744208e21a709d9453365f282449a2e9407

* Statusbar left clock: add start padding

and make it care about the right battery icon end padding
to kill people ocd

Change-Id: I99523ea340e3d93e10521a8b8178342e5a962cc4
Signed-off-by: Ded_Boi <dhanush911gtr@gmail.com>

* Protect against possible concurrent mod

java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
at java.util.ArrayList.get(ArrayList.java:437)
at com.android.systemui.recents.model.TaskStack.removeAllTasks(TaskStack.java:662)
at com.android.systemui.recents.RecentsImpl.updateHeaderBarLayout(RecentsImpl.java:782)

Change-Id: I7afd20dec213fd34e07e2241478e695068bf9d48

* SystemUI: Add missing recycle calls

Change-Id: I6e5346d9f423350e643d696299136799b78cdd28
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* backup: Fix a system server crash

 * If we get into a state where the backup data is null, system server
   will go down in flames. Abort and kill any active agents if this
   happens.

Change-Id: I65cb3c7d75a417373e8a59b9150a61b5eb1939af
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* media: Delete Media Tests

Change-Id: I350f8ae4988b5b5bcef897a4b4238d4ee1390a41
Signed-off-by: Chet Kener <Cl3Kener@gmail.com>
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* SystemUI: Adjusted animation timing

Change-Id: I7f001abe0c97167ef9bdf83b3371b0875fd1c59f
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* SystemUI: fix multi touch gestures and extra jank

The dejank utils were getting a little ahead of themselves: in between
the panel height being set to 0 (could happen often), and the user
actively trying to expand the panel, the next layout traversal from the
dejank utils would try to collapse the panel, causing bad states.

Finally, and most importantly, we need to disable motion event splitting
in our view that holds our notification panel logic so we can get multi
touch gestures in those views properly.

Ticket: CYNGNOS-2756
Change-Id: I2cda440d4e0548d3477c6fad88f7dac1cb59d9db
Signed-off-by: Roman Birg <roman@cyngn.com>
Signed-off-by: mydongistiny <jaysonedson@gmail.com>
Signed-off-by: Ded_Boi <dhanush911gtr@gmail.com>

* frameworks: Fix Null Pointer Issue

Add a null pointer check to avoid crash while customizing quick settings
in systemui.

CRs-Fixed: 1094610
Change-Id: I03eaaaeeb8bbf7fbc91ca09eb16dd1ab559d2d6f
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* Shorten wait time for shutdown time optimization

Default 500ms delay is waitting shutdown actions done in while cycle.
Shutdown actions include broadcast,nfc,radio,wifi and mountservice.
The whole actions are ordered serial operations. This delay is too
long for broadcast/nfc/radio/wifi/mountservice shutdown. Decrease the
delay will add mActionDoneSync lock time and while cycle times, so this
delay also can't be too short. Set half will have 0.5~0.7s benefit for
shutdown time, total time from 2.4s to 1.7~1.9s, which is comparable
with ref device.

CRs-Fixed: 2023578

Change-Id: Ieb34034652c3cba1c41eadc00500d1f211c2a009
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* Avoid the restart process for launching provider killed by AMS

The case is that a content provider process killed by LowmemoryKiller while the
provider launching time. And AMS will restart it for the launching provider,and
reuse the ProcessRecord, it may be killed by AMS#updateOomAdjLocked in the end
of attachApplicationLocked for empty cached process.

After that the process will restart again, and may be killed angian, another
restart, another restart...

So, we should give time for process to launch its provider, avoid the restart
and kill circle.

Test: monkey test for 10h without related issue
Change-Id: If4be91faf804493f48d3d075799576e39561ea09
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* MountService: ensure VolumeRecord with UUID exists before modifying

A client (SystemUI) can pass in a fs UUID that doesn't exist in the
records.  Guard against this invalid input.

Change-Id: I74666c1cdd56a13efa84385b387ccb3a5d68dfc2
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* mountservice: Shut down volumes before restarting framework

 * Vold assumes that when FUSE is killed, the mount is gone. This
   isn't true with sdcardfs, since the daemon doesn't continue
   to run. Cryptfs was assuming this behavior, and the system would
   hang during decryption since the emulated storage doesn't get
   unmounted.
 * Send the shutdown command before committing suicide.

Change-Id: Ifcfa63f0499a717f34482754cea95b90622290c6
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* mountservice: Don't nuke all volumes when decrypting

 * Instead, just unmount the emulated internal volume since
   it's the only one which can prevent cryptfs from restarting.

Change-Id: I757babaf763b4ef789b165d116da0708a3530e99
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* SystemUI: Rotation button can't work at first time after rotate screen

RootCase:If QS panel is not fully collapsed, all the QS tiles' state
will be clean without updated when device is switched between
landscape and portrait
Solution:Always update the state after the QS tile state is clean

CRs-Fixed: 2215731
Change-Id: Ic22cc347534056edf06d40d76b743bc9d8784a2c
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* display: Disable scaling on display mode switch

This change forces to use the default display width and height for
projection even if the application requests to switch to extended
display modes. HAL scales based on the requested display mode.

Test: This path is base on the MUT support more than one mode.
1) Check if the DUT support more than one modes with command:
   (Notes： Manufactor can use another path to save mode info)
   $ adb shell cat sys/class/graphics/fb0/modes
     1080x1920
     2160x3840
2) While the MUT support more than one mode and app set the value of
   preferredDisplayModeId (member of WindowManager.LayoutParams)
   greater than 1 as below, the app will show abnormal if without
   this patch.
   // sample
   WindowManager.LayoutParams params = getWindow().getAttributes();
   params.preferredDisplayModeId = 2;

Change-Id: Ia5260f852a52c2aae18a1a843ca97363467fb082
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* Fix wakelock being held during bootup and idle scenario

On bootup of device, if device is kept idle without unlocking the
screen the TCXO does not happen due to "ActivityManager-Sleep"
partial wake_lock being held.

Fix releases the wakelock irrespective of the result of code flow
in checkReadyForSleepLocked() function.

Change-Id: I5a61463aa29ac5e94020111b93b7eba2ba170513
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* system_server: Fix deadlock of PlayerBase.mLock and PlaybackActivityMonitor.mPlayerLock

Since system_server can have its own players, the calls to
AudioService from PlayerBase can be synchronous, hence the
deadlock.

The fix consists in never holding the lock in PlayerBase
while calling into AudioService.
Refactor the playstate update into a method used for
start / stop / pause.

Bug: 72294559
Test: see bug
Change-Id: Ib41045de124683a7484184cf63577bd2412d1362
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* SystemUI: stop crashing qs tiles during boot

this triggers my ocd
continues a579c2430f1a0bf088023b4283dcec37776c070d

Change-Id: I31719b595cb50a330f26e25074243e04c06f63c1
Signed-off-by: mydongistiny <jaysonedson@gmail.com>
Signed-off-by: Ded_Boi <dhanush911gtr@gmail.com>

* ConnectivityService doesn't send decreased score to factories at need

When there is more than one network, after Score of a network fell down
requests of that network are removed from its "networkRequests" during
process of rematchNetworkAndRequests().

As a result, current implementation of updateNetworkScore()
cannot send score of that network in sendUpdatedScoreToFactories().
This may prevent other network factories from updating their status,
e.g. TelephonyNetworkFactory cannot enable APN.

Therefore, we add process of sending decreased score into
rematchNetworkAndRequests() to fix the issue.

Bug: 29030667
Change-Id: I49c5dca475ae0e257ca853a1288fc57d68950ed9
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* Send broadcast to MediaScannerReceiver to refresh gallery

After restore file, the pics can only be seen in FileManager,
so send broadcast to MediaScannerReceiver to refresh the datebase,
then the pics can be seen in the gallery.

Change-Id: I43cd8edc0c96c1d845314c7760b367f85485a6e5
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* media/jni: Check mute state before starting play

When playing in SoundPool, PlayerBase checks
hasAppOpsPlayAudio and calls mute function.
After that, if a new audiotrack is created,
sets the volume regardless of whether mMuted.

Test: Enter DnD mode and play music file with SoundPool

Change-Id: I914e19903ff546f730f6edffdb67d4ffd05ddd0c
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* Overscroll: modified velocitytracker

Velocitytracker and overscroll are called on every touch event to
calculate if there is a scrolling/fling. Move this and the recycling
to static voids so they are pre-optimized at compile time rather than
after evoking the method call during runtime (JIT) to increase responsiveness.

Change-Id: Ic7351da58f29281ca2b6a788386b95b68b552390
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* Fix array exception in createAutoBrightnessSpline

Function does not check array lenghts and thus can cause bootloops
if brightness array configurations are invalid (different issue).

Change-Id: I8614aeb810c088b9d0274e54696856671bdcfde9
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* backup: Fix system_server crash caused by schedule version error

https://issuetracker.google.com/issues/62244702

Change-Id: I1b0bad2b854c6d877f65dec10bcfbed470881e02
Signed-off-by: pengzhicai <pengzhicai@xiaomi.com>
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* Abort connecting to native daemon during shutdown

Symptom:
System_server crashed due to unsolved "netd" service.

Root cause:
Init intentionally killed services when shutdown was triggered.
NativeDaemonConnector unnecessarily tried to reconnect the killed
daemon and NetworkManagemantService got a callback of connection.
Finally, NetworkManagemantService failed to get netd service and it
crashed with NPE.

Solution:
Do not retry connecting to the target native daemon when the device
is in the middle of shutdown.

Bug: 64237349
Change-Id: I2514cdc47b3eea785b5ffe5bd8bb27609bcc1726
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* ActivityManager: fix service could not be started correctly when app.thread == null

there is not thread object attached to application when starting service,
will not start process, so make start service failed.

startActivity, broadcast or  provider all have condition:
 if app == null || app.thread == null,  that will start process.
but startService only if app == null, lack of  condition app.thread == null,  that will start process.

https://code.google.com/p/android/issues/detail?id=224966

Change-Id: I61d9f1d3fef97a33333bd7c68be3b46f683f169c
Signed-off-by: yuanhuihui <yuanhuihui@xiaomi.com>
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* ActivityManager: Handle application crash in new thread

The system server will watchdog reboot when the binder thread
be application crash transaction exhaustion at same time.

https://code.google.com/p/android/issues/detail?id=225484

Change-Id: Ie31a894de9c64d9d639bfcd1fd18acd065780ecd
Signed-off-by: songjinshi <songjinshi@xiaomi.com>
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* ActivityManager: clean up pending broadcast receviers when force stop package

when app was force-stop, only clean up mOrderedBroadcasts and mParallelBroadcasts,
maybe exist broadcast receviers in pendind list, need clean up it completely.

AMS.forceStopPackage
    AMS.forceStopPackageLocked
        cleanupDisabledPackageReceiversLocked

Change-Id: Ic62241b04863efb51448924c9387cee844e49739
Signed-off-by: yuanhuihui <yuanhuihui@xiaomi.com>
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* frameworks/base: Fix ContentService JNI leaks

- A list of ObserverCall(s) is created by ContentService as
  it notifies changes to the registered content observers.
  Clear observer after use.

- If same Observer and same URI are registered, the callback
  functions are called multiple times when data identified by
  a given content URI changes. It makes system slow and it
  cause ANR sometimes. And when run
  unregisterContentObserver(), just one deleted but others
  are remained in mObservers. So add prevent code to avoid
  to duplicated registration of Observers

CRs-Fixed: 868634

Change-Id: I5906f581f4beaed04af09e5b9e3999f67d94f1fc
Signed-off-by: mydongistiny <jaysonedson@gmail.com>

* schedule vsync immediately when requested from the Looper thread

This patch allows Choreographer to schedule vsync immediately when it
is requested from the Looper thread. Previously this is not allowed
when vsync is already scheduled from a binder thread and hence there
is a delay up to 16ms (one vsync interval) in processing frame
callbacks.

Change-Id: Idd70f1a6c359e92ecebd778a104b71dfa6660c79
Signed-off-by: Dohyun Lee <dohyun.lee@lge.com>
Signed-off-by: mydongistiny <jaysonedson@gmail.com>